### 404
GET http://localhost:3333

### List all messages

GET http://localhost:3333/messages


### Create a new message
POST http://localhost:3333/messages
content-type: application/json

{
  "content": "hi there 2"
}


### Get a particular message by ID
GET http://localhost:3333/messages/d979d84e-d5ae-4182-9294-ad8fed44aff4


### Get a particular message by ID (404)
GET http://localhost:3333/messages/invalid-id